### ISSUE TITLE
Question: Target Specific IP

### ISSUE THREAD

**Issue by TGTGamer** [luiscript/react-native-osc#1]
Heya,

Just wondering if you could explain how to target a specific IP which is on the network?

For instance, 
React Android: Using your RN script, sends message to Server
Server: Listens for OSC on IP 10.0.0.1

Many thanks in advance.

**Comment by luiscript** [comment]
Hey!

Just create your client with the desired IP address instead of "localhost", like this:

```javascript
osc.createClient("10.0.0.1", 9090);
osc.sendMessage("/address/", [1.0, 0.0]);
```

I have noticed that when you create a Server, you need to deactivate Fast Refresh in your device. But AFAIK creating a client (like in your case) there's no problem with Fast Refresh. 

I hope it helps.

**Comment by luiscript** [comment]
I'm closing this issue, please let me know if you have any problem.
