### ISSUE TITLE
Sending message over USB Serial Port instead of IP

### ISSUE THREAD

**Issue by kgstew** [luiscript/react-native-osc#2]
I'm trying to send OSC to an Arduino using a USB connection. Is it possible to set the client address to a serial port instead of an IP address?

**Comment by luiscript** [comment]
This module integrates SwiftOSC for iOS and JavaOSC for Android, neither of the two implements a serial port communication, I don't think this is going to happen any time soon, sorry about that. 

Please let me know if you have any other question.
