### ISSUE TITLE
use ints and floats instead of doubles in android

### ISSUE THREAD

**Issue by josephlarralde** [luiscript/react-native-osc#3]
Hi Luis,
Thanks a lot for your work on this plugin.
I was testing the android version, and I realized I was only able to pass around strings and booleans (using max/msp and pure data as test OSC servers). 
I noticed that all numbers are passed as doubles by default. I could see the typetag `'d'` in pure data's console, but I'm not sure this is very standard OSC (it displays a value of `0.` in max and throws an error in pure data).
What I know is that floats (typetag `'f'`) are a very standard OSC type, as well as integers (typetag `'i'`), so I made a fork of your plugin and modified the `sendMessage` method in `OscModule.java` so that it casts any number argument to an int or a float depending on the value.
Now everything is working as expected on my side.
Would you mind me to create a PR ?
I'm not sure if it would break anything for actual users of the plugin who might need double precision data for very specific uses ... if it's the case please let me know.
Also, I didn't check the swift version yet but will do soon for sure.

**Comment by luiscript** [comment]
Hello Joseph,

This is great, thank you so much for your contribution, I believe this is done correctly on the Swift side but I haven't noticed the problem on Android. I will create a PR to fix it with your code and I will publish and update to the npm package.

Nice to see that you're using max/msp and pure data, I will love to see more about how you are integrating the plug-in into your work. If you have an specific project using react-native-osc that you would like to share, I can add it to the README file.

**Comment by josephlarralde** [comment]
Great ! Thanks for the quick update.

Actually I'm not sure it's perfect, as any type which is not a booean, a number or a string is sent as a string ... 
I think it's better than before anyways, and it fits what is announced in the README (BTW, I don't know for iOS, but the `'s'` typetag was already working on Android), so this update shouldn't break anything.
So I guess we can close this issue :)

The project I'm working on is the next version of Streamo, a very simple OSC streaming application targeting education which streams the phone's sensors and also shows some fancy real-time visualizations. It is part of the movuino ecosystem, you can learn more on www.movuino.com. The actual version on the Play Store is rather old and is based on Cordova. I'll happily let you know when the new RN based version is released (hopefully soon, but I need to fix some fluctuating udp sending rate first)

Cheers !
